### ISSUE TITLE
IC part numbers

### ISSUE THREAD

**Issue by btmills** [device-teardowns/coway-ap1512hh#1]
Thank you for publishing this resource!

Do you have the part numbers for IC1 and IC3 on the control board? I wasn’t able to make them out from the board photo you shared.

**Comment by larryqiann** [comment]
IC1: 
D78F0513A
1514XMO17

MYS

IC3:
ATMLH442
02CM       B
4W6780

**Comment by larryqiann** [comment]
This information has been added to the document. Thank you for bringing this to my attention.

**Comment by btmills** [comment]
Very helpful, thank you!
