### ISSUE TITLE
Do you have any pictures on how to disassemble the plastic vent portion from the main housing?

### ISSUE THREAD

**Issue by druess** [device-teardowns/coway-ap1512hh#4]
Hi, do you have any pictures that show how the plastic vent with grid lines are disassembled from the main housing?  I hope that makes sense.

I'm hoping to be able to remove that plastic vent with grid lines (the part that protects people from sticking there fingers or other objects into where you can see the fan rotating) without opening up the entire case.  

Thanks

**Comment by druess** [comment]
I guess the air outlet is what I'm referring too, as it's called in the manual.

**Comment by larryqiann** [comment]
This component is attached inside to the front or back case (unable to determine at the moment). It appears to be removable, but some disassembly would be required to access this part.

**Comment by druess** [comment]
Hey thanks for the quick reply! Yeah, I ended opening it up and realized it curves around underneath and is attached to the top plastic portion where the controls are. That's okay! Time to think up another solution :)
