### ISSUE TITLE
Update/Questions on DIY controls - pwm for fan control?

### ISSUE THREAD

**Issue by asmykowski93** [device-teardowns/coway-ap1512hh#7]
Do you happen to know the frequency of the pwm signal to control the fan?

Also do you happen to know exactly what pin on the power board is for fan speed control?

Looking to control fan speed with a RaspberryPi :)

Just wondering if you have any idea on this. No worries if you don't! I know i very much so risk breaking it or hurting myself trying this lol :)

**Comment by larryqiann** [comment]
Update Jun 2, 2024: I have published a design for an open source replacement main PCB. I don't know if I will be able to provide support for it, but it is provided as-is for your use (https://github.com/larryqiann/AP1512HH-ESP32/) 

In this page should be all of the information you are looking for. Please be sure to read through it carefully as it should contain all of the relevant information for your project. Feel free to let me know if you have any questions

I would recommend opening an issue there if you have further questions

**Comment by asmykowski93** [comment]
Amazing, you the best!

**Comment by alibosworth** [comment]
@larryqiann thank you for this information and for your replacement PCB design.  I was wondering if you did any investigating into the "DEBUGGING" header? I assume nothing is connected to it but it exposes some useful pins?
